spring:
  profiles:
    active: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 8080


logging:
  level:
    ru.edu.module12: info
  file:
    path: userService.log

service:
  description: User service
  version: 1.0 BETA

# SPRING_PROFILES_ACTIVE=devFILES_ACTIVE=dev